function total_TR = time_dep_TR_new_wSigma_twoP( ...
    nbd,energyi,mut,TF_conc_t,...
    RNApH_conc_t,RNApA_conc_t,...
    vmax_array_s,group_array_s,...
    vmax_array_v,group_array_v,...
    vmax_array_sv,group_array_sv)
%% generate time dependent TR (fake data) to get an intuition about real data
total_TR = zeros(length(TF_conc_t),1);

for tt = 1:length(TF_conc_t)
    TR_all = ...
    transcription_rate_new_twoP( ...
    nbd,energyi,mut,TF_conc_t(tt),...
    RNApH_conc_t(tt),RNApA_conc_t(tt),...
    vmax_array_s,group_array_s,...
    vmax_array_v,group_array_v,...
    vmax_array_sv,group_array_sv);

    total_TR(tt) = TR_all;
end

end
